version: "3.9"

services:
  frontend:
    container_name: "nginx_web"
    build:
      context: ./
      dockerfile: ./docker/build/nginx.Dockerfile
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
     - ./frontend/:/usr/share/nginx/html
     - v_frontend_node_modules:/usr/share/nginx/html/node_modules
     - v_frontend_dist:/usr/share/nginx/html/dist

  backend:
    container_name: "${CTNR_NAME}"
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/build/apache.Dockerfile
    env_file:
      - .env
    ports:
      - '${WWW_HOST_PORT}:${WWW_CTNR_PORT}'
      - '${SSL_HOST_PORT}:${SSL_CTNR_PORT}'
    links:
      - keycloak
    volumes:
      - '${PATH_HOST_WWW}:${PATH_CTNR_WWW}:rw'
      - '${PATH_HOST_CERTS}:${PATH_CTNR_CERTS}:rw'
      - ./docker/apache/logs:/var/log/apache2:rw
      - v_backend_vendor:/var/www/html/vendor
      - v_backend_dist:/var/www/html/dist

  keycloak:
    container_name: "keycloak_web"
    image: quay.io/keycloak/keycloak
    command: start-dev
    volumes:
      - ./docker/ssl:/etc/x509/https
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_FRONTEND_HOSTNAME=app.keycloak.com
      - KEYCLOAK_ADMIN_URL=https://app.keycloak.com:8443/

      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_HTTPS_PORT=8443
      - KEYCLOAK_HOSTNAME=app.keycloak.com

      - KC_DB=mysql
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KC_DB_URL_HOST=keycloak_db
      - KC_DB_URL_PORT=3306
      - KC_DB_SCHEMA=keycloak

      - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/app.keycloak.com.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/app.keycloak.com.key
    links:
      - keycloak_db
    depends_on:
      - keycloak_db

  keycloak_db:
    container_name: "keycloak_db"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3360:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - "v_keycloak_db:/var/lib/mysql:rw"

volumes:
  v_keycloak_db:
  v_backend_vendor:
  v_backend_dist:
  v_frontend_node_modules:
  v_frontend_dist: